# Function module definition file, generated by ELLEC
FUN_OFILES = \
	eef1.o\
	eef2.o\
	eebuff.o\
	eefile.o\
	eefd.o\
	eecmds.o\
	eehelp.o\
	eekmac.o\
	eef3.o\
	eesrch.o\
	eequer.o\
	eefill.o\
	eemain.o\
	eeerr.o\
	eediag.o
