#
# Makefile for the Atari ST - Sozobon C Compiler
#

CFLAGS = -O

.c.o:
	$(CC) -c $(CFLAGS) $<
	ar rv vi.lib $*.o

MACH =	tos.o

OBJ =	main.o edit.o linefunc.o normal.o cmdline.o hexchars.o \
	misccmds.o help.o ptrfunc.o search.o alloc.o mark.o \
	regexp.o regsub.o \
	screen.o fileio.o param.o undo.o version.o $(MACH)

all : stevie.ttp

stevie.ttp : $(OBJ)
	$(CC) vi.lib -o stevie.ttp

clean :
	$(RM) $(OBJ) vi.lib
